version: '3.8'

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./backend:/backend
        restart: always
        depends_on:
          - postgres-base
        networks:
            - good_network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./frontend:/frontend
        restart: always
        depends_on:
          - backend
          - postgres-base
        networks:
            - good_network

    postgres-base:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=headbase
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        networks:
            - good_network
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
          interval: 5s
          timeout: 5s
          retries: 5

networks:
  good_network:

volumes:
  pgdata:
